// Code generated by MockGen. DO NOT EDIT.
// Source: ingress.go
//
// Generated by this command:
//
//	mockgen -source=ingress.go -destination=../../test/mocks/mock_ingressrepo.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	coreentity "proletariat-budget-core/core/domain/coreentity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIngress is a mock of Ingress interface.
type MockIngress struct {
	ctrl     *gomock.Controller
	recorder *MockIngressMockRecorder
	isgomock struct{}
}

// MockIngressMockRecorder is the mock recorder for MockIngress.
type MockIngressMockRecorder struct {
	mock *MockIngress
}

// NewMockIngress creates a new mock instance.
func NewMockIngress(ctrl *gomock.Controller) *MockIngress {
	mock := &MockIngress{ctrl: ctrl}
	mock.recorder = &MockIngressMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngress) EXPECT() *MockIngressMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIngress) Create(ctx context.Context, ingress coreentity.Ingress) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ingress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIngressMockRecorder) Create(ctx, ingress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIngress)(nil).Create), ctx, ingress)
}

// GetByID mocks base method.
func (m *MockIngress) GetByID(ctx context.Context, id string) (coreentity.Ingress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(coreentity.Ingress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIngressMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIngress)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockIngress) List(ctx context.Context, params coreentity.IngressListParams) (coreentity.IngressList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(coreentity.IngressList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIngressMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIngress)(nil).List), ctx, params)
}
