// Code generated by MockGen. DO NOT EDIT.
// Source: app_config.go
//
// Generated by this command:
//
//	mockgen -source=app_config.go -destination=../../test/mocks/mock_app_config_repo.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	port "proletariat-budget-core/core/port"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAppConfig is a mock of AppConfig interface.
type MockAppConfig struct {
	ctrl     *gomock.Controller
	recorder *MockAppConfigMockRecorder
	isgomock struct{}
}

// MockAppConfigMockRecorder is the mock recorder for MockAppConfig.
type MockAppConfigMockRecorder struct {
	mock *MockAppConfig
}

// NewMockAppConfig creates a new mock instance.
func NewMockAppConfig(ctrl *gomock.Controller) *MockAppConfig {
	mock := &MockAppConfig{ctrl: ctrl}
	mock.recorder = &MockAppConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppConfig) EXPECT() *MockAppConfigMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppConfig) Create(ctx context.Context, appConfig port.AppConfig) (*port.AppConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, appConfig)
	ret0, _ := ret[0].(*port.AppConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAppConfigMockRecorder) Create(ctx, appConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppConfig)(nil).Create), ctx, appConfig)
}

// Get mocks base method.
func (m *MockAppConfig) Get(ctx context.Context) (*port.AppConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*port.AppConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAppConfigMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAppConfig)(nil).Get), ctx)
}

// Update mocks base method.
func (m *MockAppConfig) Update(ctx context.Context, appConfig port.AppConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, appConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAppConfigMockRecorder) Update(ctx, appConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAppConfig)(nil).Update), ctx, appConfig)
}
