// Code generated by MockGen. DO NOT EDIT.
// Source: expenditure.go
//
// Generated by this command:
//
//	mockgen -source=expenditure.go -destination=../../test/mocks/mock_expenditurerepo.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	coreentity "proletariat-budget-core/core/domain/coreentity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExpenditure is a mock of Expenditure interface.
type MockExpenditure struct {
	ctrl     *gomock.Controller
	recorder *MockExpenditureMockRecorder
	isgomock struct{}
}

// MockExpenditureMockRecorder is the mock recorder for MockExpenditure.
type MockExpenditureMockRecorder struct {
	mock *MockExpenditure
}

// NewMockExpenditure creates a new mock instance.
func NewMockExpenditure(ctrl *gomock.Controller) *MockExpenditure {
	mock := &MockExpenditure{ctrl: ctrl}
	mock.recorder = &MockExpenditureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenditure) EXPECT() *MockExpenditureMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExpenditure) Create(ctx context.Context, expenditure coreentity.Expenditure) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, expenditure)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExpenditureMockRecorder) Create(ctx, expenditure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExpenditure)(nil).Create), ctx, expenditure)
}

// DeleteTemplate mocks base method.
func (m *MockExpenditure) DeleteTemplate(ctx context.Context, template coreentity.Expenditure) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockExpenditureMockRecorder) DeleteTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockExpenditure)(nil).DeleteTemplate), ctx, template)
}

// FindExpenditures mocks base method.
func (m *MockExpenditure) FindExpenditures(ctx context.Context, queryParams coreentity.ExpenditureListParams) (*coreentity.ExpenditureList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpenditures", ctx, queryParams)
	ret0, _ := ret[0].(*coreentity.ExpenditureList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpenditures indicates an expected call of FindExpenditures.
func (mr *MockExpenditureMockRecorder) FindExpenditures(ctx, queryParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpenditures", reflect.TypeOf((*MockExpenditure)(nil).FindExpenditures), ctx, queryParams)
}

// GetByID mocks base method.
func (m *MockExpenditure) GetByID(ctx context.Context, id string) (*coreentity.Expenditure, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*coreentity.Expenditure)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockExpenditureMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockExpenditure)(nil).GetByID), ctx, id)
}

// UpdateTemplate mocks base method.
func (m *MockExpenditure) UpdateTemplate(ctx context.Context, template coreentity.Expenditure) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockExpenditureMockRecorder) UpdateTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockExpenditure)(nil).UpdateTemplate), ctx, template)
}
