// Code generated by MockGen. DO NOT EDIT.
// Source: task_processor.go
//
// Generated by this command:
//
//	mockgen -source=task_processor.go -destination=../../test/mocks/mock_task_processor.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	coreentity "proletariat-budget-core/core/domain/coreentity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskProcessor is a mock of TaskProcessor interface.
type MockTaskProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskProcessorMockRecorder
	isgomock struct{}
}

// MockTaskProcessorMockRecorder is the mock recorder for MockTaskProcessor.
type MockTaskProcessorMockRecorder struct {
	mock *MockTaskProcessor
}

// NewMockTaskProcessor creates a new mock instance.
func NewMockTaskProcessor(ctrl *gomock.Controller) *MockTaskProcessor {
	mock := &MockTaskProcessor{ctrl: ctrl}
	mock.recorder = &MockTaskProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskProcessor) EXPECT() *MockTaskProcessorMockRecorder {
	return m.recorder
}

// ProcessTask mocks base method.
func (m *MockTaskProcessor) ProcessTask(ctx context.Context, task coreentity.RecurrencePattern) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockTaskProcessorMockRecorder) ProcessTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockTaskProcessor)(nil).ProcessTask), ctx, task)
}
