// Code generated by MockGen. DO NOT EDIT.
// Source: savings_goal.go
//
// Generated by this command:
//
//	mockgen -source=savings_goal.go -destination=../../test/mocks/mock_savings_goalrepo.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"proletariat-budget-core/core/domain/coreentity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSavingsGoal is a mock of SavingsGoal interface.
type MockSavingsGoal struct {
	ctrl     *gomock.Controller
	recorder *MockSavingsGoalMockRecorder
	isgomock struct{}
}

// MockSavingsGoalMockRecorder is the mock recorder for MockSavingsGoal.
type MockSavingsGoalMockRecorder struct {
	mock *MockSavingsGoal
}

// NewMockSavingsGoal creates a new mock instance.
func NewMockSavingsGoal(ctrl *gomock.Controller) *MockSavingsGoal {
	mock := &MockSavingsGoal{ctrl: ctrl}
	mock.recorder = &MockSavingsGoalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSavingsGoal) EXPECT() *MockSavingsGoalMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSavingsGoal) Create(ctx context.Context, savingsGoal coreentity.SavingsGoal) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, savingsGoal)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSavingsGoalMockRecorder) Create(ctx, savingsGoal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSavingsGoal)(nil).Create), ctx, savingsGoal)
}

// CreateContribution mocks base method.
func (m *MockSavingsGoal) CreateContribution(ctx context.Context, contribution coreentity.SavingsContribution) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContribution", ctx, contribution)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContribution indicates an expected call of CreateContribution.
func (mr *MockSavingsGoalMockRecorder) CreateContribution(ctx, contribution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContribution", reflect.TypeOf((*MockSavingsGoal)(nil).CreateContribution), ctx, contribution)
}

// CreateWithdrawal mocks base method.
func (m *MockSavingsGoal) CreateWithdrawal(ctx context.Context, withdrawal coreentity.SavingsWithdrawal) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", ctx, withdrawal)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockSavingsGoalMockRecorder) CreateWithdrawal(ctx, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockSavingsGoal)(nil).CreateWithdrawal), ctx, withdrawal)
}

// Delete mocks base method.
func (m *MockSavingsGoal) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSavingsGoalMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSavingsGoal)(nil).Delete), ctx, id)
}

// DeleteContribution mocks base method.
func (m *MockSavingsGoal) DeleteContribution(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContribution", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContribution indicates an expected call of DeleteContribution.
func (mr *MockSavingsGoalMockRecorder) DeleteContribution(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContribution", reflect.TypeOf((*MockSavingsGoal)(nil).DeleteContribution), ctx, id)
}

// DeleteWithdrawal mocks base method.
func (m *MockSavingsGoal) DeleteWithdrawal(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithdrawal", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithdrawal indicates an expected call of DeleteWithdrawal.
func (mr *MockSavingsGoalMockRecorder) DeleteWithdrawal(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithdrawal", reflect.TypeOf((*MockSavingsGoal)(nil).DeleteWithdrawal), ctx, id)
}

// GetByID mocks base method.
func (m *MockSavingsGoal) GetByID(ctx context.Context, id string) (*coreentity.SavingsGoal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*coreentity.SavingsGoal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSavingsGoalMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSavingsGoal)(nil).GetByID), ctx, id)
}

// GetContributionByID mocks base method.
func (m *MockSavingsGoal) GetContributionByID(ctx context.Context, id string) (*coreentity.SavingsContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContributionByID", ctx, id)
	ret0, _ := ret[0].(*coreentity.SavingsContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContributionByID indicates an expected call of GetContributionByID.
func (mr *MockSavingsGoalMockRecorder) GetContributionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContributionByID", reflect.TypeOf((*MockSavingsGoal)(nil).GetContributionByID), ctx, id)
}

// GetWithdrawalByID mocks base method.
func (m *MockSavingsGoal) GetWithdrawalByID(ctx context.Context, id string) (*coreentity.SavingsWithdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalByID", ctx, id)
	ret0, _ := ret[0].(*coreentity.SavingsWithdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalByID indicates an expected call of GetWithdrawalByID.
func (mr *MockSavingsGoalMockRecorder) GetWithdrawalByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalByID", reflect.TypeOf((*MockSavingsGoal)(nil).GetWithdrawalByID), ctx, id)
}

// List mocks base method.
func (m *MockSavingsGoal) List(ctx context.Context) ([]coreentity.SavingsGoal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]coreentity.SavingsGoal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSavingsGoalMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSavingsGoal)(nil).List), ctx)
}

// ListSavingsTransactions mocks base method.
func (m *MockSavingsGoal) ListSavingsTransactions(ctx context.Context, params coreentity.ListSavingsTransactionsParams) (*coreentity.SavingsTransactionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSavingsTransactions", ctx, params)
	ret0, _ := ret[0].(*coreentity.SavingsTransactionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSavingsTransactions indicates an expected call of ListSavingsTransactions.
func (mr *MockSavingsGoalMockRecorder) ListSavingsTransactions(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSavingsTransactions", reflect.TypeOf((*MockSavingsGoal)(nil).ListSavingsTransactions), ctx, params)
}

// MarkAsAbandoned mocks base method.
func (m *MockSavingsGoal) MarkAsAbandoned(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsAbandoned", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsAbandoned indicates an expected call of MarkAsAbandoned.
func (mr *MockSavingsGoalMockRecorder) MarkAsAbandoned(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsAbandoned", reflect.TypeOf((*MockSavingsGoal)(nil).MarkAsAbandoned), ctx, id)
}

// MarkAsCompleted mocks base method.
func (m *MockSavingsGoal) MarkAsCompleted(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsCompleted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsCompleted indicates an expected call of MarkAsCompleted.
func (mr *MockSavingsGoalMockRecorder) MarkAsCompleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsCompleted", reflect.TypeOf((*MockSavingsGoal)(nil).MarkAsCompleted), ctx, id)
}

// Update mocks base method.
func (m *MockSavingsGoal) Update(ctx context.Context, id string, savingsGoal coreentity.SavingsGoal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, savingsGoal)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSavingsGoalMockRecorder) Update(ctx, id, savingsGoal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSavingsGoal)(nil).Update), ctx, id, savingsGoal)
}
