// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_manager.go
//
// Generated by this command:
//
//	mockgen -source=transaction_manager.go -destination=../../test/mocks/mock_transaction_manager.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	port "proletariat-budget-core/core/port"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
	isgomock struct{}
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// WithDatabaseTransaction mocks base method.
func (m *MockTransactionManager) WithDatabaseTransaction(ctx context.Context, fn func(context.Context, port.TransactionContext) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDatabaseTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithDatabaseTransaction indicates an expected call of WithDatabaseTransaction.
func (mr *MockTransactionManagerMockRecorder) WithDatabaseTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDatabaseTransaction", reflect.TypeOf((*MockTransactionManager)(nil).WithDatabaseTransaction), ctx, fn)
}

// MockTransactionContext is a mock of TransactionContext interface.
type MockTransactionContext struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionContextMockRecorder
	isgomock struct{}
}

// MockTransactionContextMockRecorder is the mock recorder for MockTransactionContext.
type MockTransactionContextMockRecorder struct {
	mock *MockTransactionContext
}

// NewMockTransactionContext creates a new mock instance.
func NewMockTransactionContext(ctrl *gomock.Controller) *MockTransactionContext {
	mock := &MockTransactionContext{ctrl: ctrl}
	mock.recorder = &MockTransactionContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionContext) EXPECT() *MockTransactionContextMockRecorder {
	return m.recorder
}

// GetAccountRepo mocks base method.
func (m *MockTransactionContext) GetAccountRepo() port.Account {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountRepo")
	ret0, _ := ret[0].(port.Account)
	return ret0
}

// GetAccountRepo indicates an expected call of GetAccountRepo.
func (mr *MockTransactionContextMockRecorder) GetAccountRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountRepo", reflect.TypeOf((*MockTransactionContext)(nil).GetAccountRepo))
}

// GetCategoryRepo mocks base method.
func (m *MockTransactionContext) GetCategoryRepo() port.Category {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryRepo")
	ret0, _ := ret[0].(port.Category)
	return ret0
}

// GetCategoryRepo indicates an expected call of GetCategoryRepo.
func (mr *MockTransactionContextMockRecorder) GetCategoryRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryRepo", reflect.TypeOf((*MockTransactionContext)(nil).GetCategoryRepo))
}

// GetExpenditureRepo mocks base method.
func (m *MockTransactionContext) GetExpenditureRepo() port.Expenditure {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpenditureRepo")
	ret0, _ := ret[0].(port.Expenditure)
	return ret0
}

// GetExpenditureRepo indicates an expected call of GetExpenditureRepo.
func (mr *MockTransactionContextMockRecorder) GetExpenditureRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpenditureRepo", reflect.TypeOf((*MockTransactionContext)(nil).GetExpenditureRepo))
}

// GetIngressRepo mocks base method.
func (m *MockTransactionContext) GetIngressRepo() port.Ingress {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIngressRepo")
	ret0, _ := ret[0].(port.Ingress)
	return ret0
}

// GetIngressRepo indicates an expected call of GetIngressRepo.
func (mr *MockTransactionContextMockRecorder) GetIngressRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIngressRepo", reflect.TypeOf((*MockTransactionContext)(nil).GetIngressRepo))
}

// GetTagsRepo mocks base method.
func (m *MockTransactionContext) GetTagsRepo() port.Tags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsRepo")
	ret0, _ := ret[0].(port.Tags)
	return ret0
}

// GetTagsRepo indicates an expected call of GetTagsRepo.
func (mr *MockTransactionContextMockRecorder) GetTagsRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsRepo", reflect.TypeOf((*MockTransactionContext)(nil).GetTagsRepo))
}

// GetTransactionRepo mocks base method.
func (m *MockTransactionContext) GetTransactionRepo() port.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionRepo")
	ret0, _ := ret[0].(port.Transaction)
	return ret0
}

// GetTransactionRepo indicates an expected call of GetTransactionRepo.
func (mr *MockTransactionContextMockRecorder) GetTransactionRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionRepo", reflect.TypeOf((*MockTransactionContext)(nil).GetTransactionRepo))
}

// GetTransferRepo mocks base method.
func (m *MockTransactionContext) GetTransferRepo() port.Transfer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransferRepo")
	ret0, _ := ret[0].(port.Transfer)
	return ret0
}

// GetTransferRepo indicates an expected call of GetTransferRepo.
func (mr *MockTransactionContextMockRecorder) GetTransferRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransferRepo", reflect.TypeOf((*MockTransactionContext)(nil).GetTransferRepo))
}
