// Code generated by MockGen. DO NOT EDIT.
// Source: ticker_provider.go
//
// Generated by this command:
//
//	mockgen -source=ticker_provider.go -destination=../../test/mocks/mock_ticker_provider.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTickerProvider is a mock of TickerProvider interface.
type MockTickerProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTickerProviderMockRecorder
	isgomock struct{}
}

// MockTickerProviderMockRecorder is the mock recorder for MockTickerProvider.
type MockTickerProviderMockRecorder struct {
	mock *MockTickerProvider
}

// NewMockTickerProvider creates a new mock instance.
func NewMockTickerProvider(ctrl *gomock.Controller) *MockTickerProvider {
	mock := &MockTickerProvider{ctrl: ctrl}
	mock.recorder = &MockTickerProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTickerProvider) EXPECT() *MockTickerProviderMockRecorder {
	return m.recorder
}

// NewTicker mocks base method.
func (m *MockTickerProvider) NewTicker(duration time.Duration) *time.Ticker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTicker", duration)
	ret0, _ := ret[0].(*time.Ticker)
	return ret0
}

// NewTicker indicates an expected call of NewTicker.
func (mr *MockTickerProviderMockRecorder) NewTicker(duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTicker", reflect.TypeOf((*MockTickerProvider)(nil).NewTicker), duration)
}
