// Code generated by MockGen. DO NOT EDIT.
// Source: household_member.go
//
// Generated by this command:
//
//	mockgen -source=household_member.go -destination=../../test/mocks/mock_household_memberrepo.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	coreentity "proletariat-budget-core/core/domain/coreentity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHouseholdMember is a mock of HouseholdMember interface.
type MockHouseholdMember struct {
	ctrl     *gomock.Controller
	recorder *MockHouseholdMemberMockRecorder
	isgomock struct{}
}

// MockHouseholdMemberMockRecorder is the mock recorder for MockHouseholdMember.
type MockHouseholdMemberMockRecorder struct {
	mock *MockHouseholdMember
}

// NewMockHouseholdMember creates a new mock instance.
func NewMockHouseholdMember(ctrl *gomock.Controller) *MockHouseholdMember {
	mock := &MockHouseholdMember{ctrl: ctrl}
	mock.recorder = &MockHouseholdMemberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHouseholdMember) EXPECT() *MockHouseholdMemberMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockHouseholdMember) Activate(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockHouseholdMemberMockRecorder) Activate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockHouseholdMember)(nil).Activate), ctx, id)
}

// CanDelete mocks base method.
func (m *MockHouseholdMember) CanDelete(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanDelete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanDelete indicates an expected call of CanDelete.
func (mr *MockHouseholdMemberMockRecorder) CanDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanDelete", reflect.TypeOf((*MockHouseholdMember)(nil).CanDelete), ctx, id)
}

// Create mocks base method.
func (m *MockHouseholdMember) Create(ctx context.Context, householdMember coreentity.HouseholdMember) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, householdMember)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHouseholdMemberMockRecorder) Create(ctx, householdMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHouseholdMember)(nil).Create), ctx, householdMember)
}

// Deactivate mocks base method.
func (m *MockHouseholdMember) Deactivate(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockHouseholdMemberMockRecorder) Deactivate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockHouseholdMember)(nil).Deactivate), ctx, id)
}

// Delete mocks base method.
func (m *MockHouseholdMember) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHouseholdMemberMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHouseholdMember)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockHouseholdMember) GetByID(ctx context.Context, id string) (*coreentity.HouseholdMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*coreentity.HouseholdMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockHouseholdMemberMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockHouseholdMember)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockHouseholdMember) List(ctx context.Context, params *coreentity.HouseholdMemberListParams) (*coreentity.HouseholdMemberList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(*coreentity.HouseholdMemberList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHouseholdMemberMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHouseholdMember)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockHouseholdMember) Update(ctx context.Context, id string, householdMember coreentity.HouseholdMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, householdMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHouseholdMemberMockRecorder) Update(ctx, id, householdMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHouseholdMember)(nil).Update), ctx, id, householdMember)
}
