// Code generated by MockGen. DO NOT EDIT.
// Source: tags.go
//
// Generated by this command:
//
//	mockgen -source=tags.go -destination=../../test/mocks/mock_tagsrepo.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	coreentity "proletariat-budget-core/core/domain/coreentity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTags is a mock of Tags interface.
type MockTags struct {
	ctrl     *gomock.Controller
	recorder *MockTagsMockRecorder
	isgomock struct{}
}

// MockTagsMockRecorder is the mock recorder for MockTags.
type MockTagsMockRecorder struct {
	mock *MockTags
}

// NewMockTags creates a new mock instance.
func NewMockTags(ctrl *gomock.Controller) *MockTags {
	mock := &MockTags{ctrl: ctrl}
	mock.recorder = &MockTagsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTags) EXPECT() *MockTagsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTags) Create(ctx context.Context, tag coreentity.Tag) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTagsMockRecorder) Create(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTags)(nil).Create), ctx, tag)
}

// Delete mocks base method.
func (m *MockTags) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagsMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTags)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTags) GetByID(ctx context.Context, id string) (*coreentity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*coreentity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTagsMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTags)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockTags) GetByIDs(ctx context.Context, ids []string) (*[]*coreentity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].(*[]*coreentity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockTagsMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockTags)(nil).GetByIDs), ctx, ids)
}

// GetByNameAndType mocks base method.
func (m *MockTags) GetByNameAndType(ctx context.Context, name string, tagType coreentity.TagType) (*coreentity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNameAndType", ctx, name, tagType)
	ret0, _ := ret[0].(*coreentity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNameAndType indicates an expected call of GetByNameAndType.
func (mr *MockTagsMockRecorder) GetByNameAndType(ctx, name, tagType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNameAndType", reflect.TypeOf((*MockTags)(nil).GetByNameAndType), ctx, name, tagType)
}

// LinkTagsToType mocks base method.
func (m *MockTags) LinkTagsToType(ctx context.Context, foreignID string, tags *[]*coreentity.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkTagsToType", ctx, foreignID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkTagsToType indicates an expected call of LinkTagsToType.
func (mr *MockTagsMockRecorder) LinkTagsToType(ctx, foreignID, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkTagsToType", reflect.TypeOf((*MockTags)(nil).LinkTagsToType), ctx, foreignID, tags)
}

// List mocks base method.
func (m *MockTags) List(ctx context.Context) (*[]*coreentity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(*[]*coreentity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTagsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTags)(nil).List), ctx)
}

// ListByType mocks base method.
func (m *MockTags) ListByType(ctx context.Context, tagType coreentity.TagType, ids *[]string) (*[]*coreentity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByType", ctx, tagType, ids)
	ret0, _ := ret[0].(*[]*coreentity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByType indicates an expected call of ListByType.
func (mr *MockTagsMockRecorder) ListByType(ctx, tagType, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByType", reflect.TypeOf((*MockTags)(nil).ListByType), ctx, tagType, ids)
}

// Update mocks base method.
func (m *MockTags) Update(ctx context.Context, id string, tag coreentity.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTagsMockRecorder) Update(ctx, id, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTags)(nil).Update), ctx, id, tag)
}
