// Code generated by MockGen. DO NOT EDIT.
// Source: recurrence_pattern.go
//
// Generated by this command:
//
//	mockgen -source=recurrence_pattern.go -destination=../../test/mocks/mock_recurrence_pattern_repo.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "proletariat-budget-core/core/domain/coreentity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRecurrencePattern is a mock of RecurrencePattern interface.
type MockRecurrencePattern struct {
	ctrl     *gomock.Controller
	recorder *MockRecurrencePatternMockRecorder
	isgomock struct{}
}

// MockRecurrencePatternMockRecorder is the mock recorder for MockRecurrencePattern.
type MockRecurrencePatternMockRecorder struct {
	mock *MockRecurrencePattern
}

// NewMockRecurrencePattern creates a new mock instance.
func NewMockRecurrencePattern(ctrl *gomock.Controller) *MockRecurrencePattern {
	mock := &MockRecurrencePattern{ctrl: ctrl}
	mock.recorder = &MockRecurrencePatternMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecurrencePattern) EXPECT() *MockRecurrencePatternMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecurrencePattern) Create(ctx context.Context, recurrencePattern domain.RecurrencePattern) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, recurrencePattern)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRecurrencePatternMockRecorder) Create(ctx, recurrencePattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecurrencePattern)(nil).Create), ctx, recurrencePattern)
}

// Delete mocks base method.
func (m *MockRecurrencePattern) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecurrencePatternMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecurrencePattern)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRecurrencePattern) GetByID(ctx context.Context, id string) (*domain.RecurrencePattern, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.RecurrencePattern)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRecurrencePatternMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRecurrencePattern)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockRecurrencePattern) List(ctx context.Context) ([]domain.RecurrencePattern, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.RecurrencePattern)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRecurrencePatternMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRecurrencePattern)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockRecurrencePattern) Update(ctx context.Context, id string, recurrencePattern domain.RecurrencePattern) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, recurrencePattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecurrencePatternMockRecorder) Update(ctx, id, recurrencePattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecurrencePattern)(nil).Update), ctx, id, recurrencePattern)
}
